from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    AGENT = "AGENT"
    USER = "USER"


class TicketStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_USER = "WAITING_USER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class TicketPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TicketEventType(StrEnum):
    CREATED = "CREATED"
    TITLE_CHANGED = "TITLE_CHANGED"
    DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    CATEGORY_CHANGED = "CATEGORY_CHANGED"
    SUBCATEGORY_CHANGED = "SUBCATEGORY_CHANGED"
    TEAM_CHANGED = "TEAM_CHANGED"
    ASSIGNEE_CHANGED = "ASSIGNEE_CHANGED"
    COMMENT_ADDED = "COMMENT_ADDED"
    RESOLVED = "RESOLVED"
